import Head from 'next/head'
import Image from 'next/image'
import CoreValues from '../components/HomePageComponents/CoreValues'
import FeaturedClients from '../components/HomePageComponents/FeaturedClients'
import HeroCarousel from '../components/HomePageComponents/HeroCarousel'
import ImpactfulIdeas from '../components/HomePageComponents/ImpactfulIdeas'
import OurPurpose from '../components/HomePageComponents/OurPurpose'
import ReimagineYourCareer from '../components/HomePageComponents/ReimagineYourCareer'
import TheCoreTeam from '../components/HomePageComponents/TheCoreTeam'
import YouTubeResponsiveEmbed from '../components/shared/YouTubeResponsiveEmbed'
import { siteLink } from '../shared/data'

export default function Home() {
    return (
        < >
            <Head>
                <title>Shubhankar Consultancy</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="home-page">
                <HeroCarousel/>
                <OurPurpose/>
                <CoreValues />
                <FeaturedClients/>
                <ImpactfulIdeas/>
                <ReimagineYourCareer/>
                <TheCoreTeam/>
            </main>
        </>
    )
}
