import Head from 'next/head'
import Image from 'next/image'
import YouTubeResponsiveEmbed from '../components/shared/YouTubeResponsiveEmbed'
import { siteLink } from '../shared/data'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    < >
      <Head>
        <title>Shubhankar Consultancy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className="jumbotron text-center">
          <h1 className="h1 page-title text-center">Shubhankar Consulting</h1>
          <div className="container mt-5">
            <div className="row">
              <div className="col-md-4 offset-md-4">
                <img src={siteLink+"shubhankar-consulting.jpeg"} alt="" className="img-fluid" />
              </div>
            </div>
          </div>
        </section>
        <section className="service-intro py-5" id="intro">
                <div className="container">
                    {/* intro heading */}
                    <div className="row mb-4">
                        <div className="col-md-8">
                            <h1 className="font-44 font-weight-900">
                                Driving change by unlocking human ingenuity
                            </h1>
                        </div>
                    </div>
                    <div className="row">
                        <div className="col-md-6">
                            <p className="mb-4 font-18">
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus eveniet error veritatis deserunt obcaecati suscipit nobis officiis vero, provident praesentium in nulla repellendus soluta id rerum saepe, quos unde iure ipsa aperiam ratione. Reiciendis beatae voluptatum eveniet asperiores placeat necessitatibus!
                            </p>
                            <p className="mb-4 font-18">
                                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem, non distinctio, libero ad voluptatum molestias aliquid laboriosam corporis corrupti nobis neque ipsum commodi possimus porro reprehenderit animi sapiente?
                            </p>
                            <p className="mb-4 font-18">
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae a adipisci aspernatur ipsa voluptatibus, blanditiis dicta. Eum illum aliquam ex.
                            </p>
                        </div>
                        <div className="col-md-6">
                            <YouTubeResponsiveEmbed youTubeId="L7c4wS7T_T8" />
                        </div>
                    </div>
                </div>
            </section>
      </main>

     
    </>
  )
}
